spring.application.name=br.com.spring-security

# H2 Console configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Security Config
security.config.prefix=Bearer
# A chave deve ter pelo menos 512 bits (64 caracteres) para HS512
security.config.key=SECRET_KEY_SECRET_KEY_SECRET_KEY_SECRET_KEY_SECRET_KEY_SECRET_KEY_SECRET_KEY_SECRET_KEY
security.config.expiration=3600000

# DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

#Create a temporary user to testing
#spring.security.user.name=matheus
#spring.security.user.password=matheus123
#spring.security.user.roles=USERS